### ISSUE TITLE
BCash node is not able to download data after block : 556766

### ISSUE THREAD

**Issue by ankita-p17** [bcoin-org/bcash#114]
I am running a BCash node. It was running fine before but now encountering errors : 

![screenshot](https://user-images.githubusercontent.com/35130088/49084188-c4ff6480-f274-11e8-88ab-cb850a40b20b.png)

**Comment by pinheadmz** [comment]
So far just looks like an issue with peers, it's been 4 hours since you posted, did chain sync ever continue? Or are all peers timing out? Can you check your chain tip hash against a block explorer and make sure you're on the same chain?

**Comment by ankita-p17** [comment]
This is stuck from 15th November. The Chain is not getting updated till then. Not all the hosts are timing out but some are like stalling peers. I saw "wrong block" warning as well.

**Comment by pinheadmz** [comment]
Oh thats the date of the hard fork, are you running the latest version of bcash?

**Comment by pinheadmz** [comment]
`556766` is the last block before the fork!

**Comment by ankita-p17** [comment]
OH! No, this node I setup up 3months back. Do I need to update the node or anything. And hard fork is, BCH is forked to some other! I missed this.

**Comment by pinheadmz** [comment]
Bitcoin Cash has regularly scheduled hard forks to upgrade their protocol. Unfortunately, it requires extra attention and maintenance to stay on the main chain: https://www.bitcoincash.org/network-upgrade.html

You should update bcash asap: https://github.com/bcoin-org/bcash/releases/tag/v1.1.0

**Comment by ankita-p17** [comment]
Upgrading the existing node will give the other data for BCHABC and BCHSV both?

**Comment by pinheadmz** [comment]
Just ABC. There's no support for SV at this time.

**Comment by alwaysAn0n** [comment]
@ankita-p17 Is this issue safe to close?

**Comment by ankita-p17** [comment]
> @ankita-p17 Is this issue safe to close?

yes

**Comment by livingrock7** [comment]
Which version do you suggest? https://download.bitcoinabc.org/

I have noticed walletimport fails on older versions. Please advise!
