### ISSUE TITLE
ERR_ASSERTION when requesting UTXOs for a specific address

### ISSUE THREAD

**Issue by jeansouza** [bcoin-org/bcash#118]
When I try to get UTXOs (endpoint `/coin/address/${address}`) for the address `qqqqvm6vn3uvh6tcqk5kl0gt0ygzte5lay9yhumssf` the following error is thrown:

```
{
  "error": {
    "type": "AssertionError",
    "code": "ERR_ASSERTION",
    "message": "false == true"
  }
}
```

I installed cloning the GitHub repository, and I'm using the branch master, wich is currently updated with all commits.

For other addresses there is no error.

The following trace can be found in the log file:

```
[D:2018-12-07T19:55:46Z] (http) Request for method=GET path=/coin/address/qqqqvm6vn3uvh6tcqk5kl0gt0ygzte5lay9yhumssf (10.120.2.47).
[E:2018-12-07T19:55:46Z] (node) false == true
AssertionError [ERR_ASSERTION]: false == true
    at AddrIndexer.getCoinsByAddress (/home/ec2-user/bcash/lib/indexer/addrindexer.js:163:9)
    at <anonymous>
```

**Comment by tuxcanfly** [comment]
Thanks for reporting. Working on a PR which addresses this issue.

**Comment by jornfilho** [comment]
Hello,

This is happening to me again.
I'm using v1.1.1, same logs and even using this address `qqqqvm6vn3uvh6tcqk5kl0gt0ygzte5lay9yhumssf`it  doesn't work.

**Comment by pinheadmz** [comment]
@jornfilho Are you running code with the patch @javed indicated? #119
