### ISSUE TITLE
HTTP API Create new wallet just returns not found

### ISSUE THREAD

**Issue by andrewcottage** [bcoin-org/bcash#121]
I'm trying to create a new wallet. I have cash running on testnet. When I follow the example to create a wallet I keeps getting not found returned.

```
curl http://localhost:18332/wallet/someID \
  -X PUT \
  --data '{"passphrase":"password"}'
```

Response is
```
{
  "error": {
    "message": "Not found."
  }
}
```

I'm following the example here https://bcoin.io/api-docs/#create-a-wallet

**Comment by pinheadmz** [comment]
The http-port for wallet server on testnet is actually 18334:
http://bcoin.io/api-docs/#wallet
You may also need to include an API-KEY

**Comment by andrewcottage** [comment]
Thanks, you're right. That was the issue.
