### ISSUE TITLE
Issues when issuing RPC commands via POST 

### ISSUE THREAD

**Issue by andrewcottage** [bcoin-org/bcash#126]
I'm trying to make an RPC call. Here's an example:
```
curl http://localhost:18334 \
  -X POST \
  --data '{
    "method": "estimatefee",
    "params": [ '1' ]
  }'
```

I get this response
```
{"result":null,"error":{"message":"Method not found: estimatefee.","code":-32601},"id":null}
```

Any idea what's wrong? I've taken that example from the docs. This also happens with all other commands that I've tried.

**Comment by pinheadmz** [comment]
Try including an API key:
### bcoin.conf
```
api-key: 12345678
```

`curl x:12345678@127.0.0.1:18332 ...` etc

**Comment by andrewcottage** [comment]
I see. That works! 

Thanks a lot!
