### ISSUE TITLE
Fee rate constant

### ISSUE THREAD

**Issue by F1NYA** [bcoin-org/bcash#139]
Fee rate calculated by mempool `mempool.fees.estimateFee(targetBlock, true)` is always 1008 s/kb(for any `targetBlock`), so calculated fee is 0.00000228 bch
So transaction is broadcasted but there is no such tx on any explorer

used rojii/bcash, branch schnorr and multisig

**Comment by rojii** [comment]
The Multisig branch is experimental and subject to change this upcoming week. Are you using the bwallet-cli to send / receive transactions?

**Comment by jjgg22zh** [comment]
Do not use the multisig-branch that is simply a experimental branch for the upcoming Hard Fork in November. Btw, if you're not using the bwallet-cli to send / receive transactions i highly suggest you do. It should solve the issue that's occuring.

**Comment by F1NYA** [comment]
On `schnorr` branch same problem
`node.fees.estimateFee({any target block}, {true/false})` returns same result(last time fee based on rate was `0.000227 BCH`)
Same story with `walletdb.estimateFee({any target block})`

We can not use bwallet-cli, because we are using direct fullNode JS API by our wrapper. It's our specific choice.
Receiving, calculating confirmations and other node's functionality is ok, but the only problem is stucked transactions on send and `estimateFee` that always the same
