### ISSUE TITLE
SPV sync fails on checkpoint 1188697

### ISSUE THREAD

**Issue by GiorgosChristoglou** [bcoin-org/bcash#35]
I tried to sync my spv node and it throws a warning on the checkpoint block 1188697. 

The warning message produced is the following:
`[warning] (chain) Tried to connect invalid block: 0000000000051b450faa75bb8e1ea30bc18c4b9736e765d2794259a53bc83f99 (1188698).`

The block number 1188698 though is not invalid, since it is part of the main chain.

**Comment by tuxcanfly** [comment]
@GiorgosChristoglou should be fixed in #33

**Comment by tuxcanfly** [comment]
Fixed in 04ad23aa9b9cc3072912430c0460307fcec5856d
