### ISSUE TITLE
mempool list is null

### ISSUE THREAD

**Issue by chakhalyan1** [bcoin-org/bcash#49]
Hi. in my bcash node finished sync process, but mempool is empty. and can not get mempool transactions..
`{
version: "v1.0.0-alpha",
network: "main",
chain: {
height: 535217,
tip: "0000000000000000017b950154f3f6f5e700aaae6959e44bf7bbfa0c29f84b6f",
progress: 1,
},
pool: {
host: "localhost",
port: 8333,
agent: "/bcash:v1.0.0-alpha/",
services: "1",
outbound: 100,
inbound: 9,
},
mempool: {
tx: 0,
size: 0,
},
time: {
uptime: 277,
system: 1529326687,
adjusted: 1529326687,
offset: 0,
},
memory: {
total: 258,
jsHeap: 16,
jsHeapTotal: 18,
nativeHeap: 239,
external: 69,
},
}`

**Comment by tuxcanfly** [comment]
Fixed in 16c8e40263123eaf7d66f74e8a72910b8accc1f0
