### ISSUE TITLE
Zero transaction fee issue

### ISSUE THREAD

**Issue by Ariel-Li-Yu** [bcoin-org/bcash#73]
In this transaction data returned from bcash API, the transaction fee is zero. But actually the fee should be 0.00000229, according to other online BCH explorers. 

{
        "hash": "a3617a2302aacafc87cb40182ece014d5e89a71588abb18b3a620f778896fb47",
        "fee": 0,
        "rate": 0,
        "mtime": 1532996743,
        "height": 539748,
        "block": "00000000000000000007f2ff81048b5c71b9cb432f147be004c3196880b8544c",
        "time": 1532061390,
        "index": 296,
        "version": 1,
        "inputs": [
            {
                "prevout": {
                    "hash": "26a5e48f2fe2206925b4be6685378e4201e964db28926821ec45321dc4a3874e",
                    "index": 3
                },
                "script": "483045022100ac252ef8b1e86b5d77d50f149028e4f17a59554e1f2dd64fbd223d2396b0eda202204312ef0c7694d297d4ed5dc4f23b3587a61cd91189b23f1306cff256f60b6849412103a78fbf6f3dfd66621171630e84146e8e1df425365e44f2cef6d65e03f7fed1de",
                "sequence": 4294967295,
                "address": "bitcoincash:qrwd4ymttsk5tzuvnnaxr26ll3fl0apedupusq5fhf"
            }
        ],
        "outputs": [
            {
                "value": 80000,
                "script": "76a914a928707e4a74740cdbacf87a390c45878f64e2ae88ac",
                "address": "bitcoincash:qz5jsur7ff68grxm4nu85wgvgkrc7e8z4ce66elguv"
            },
            {
                "value": 9809771,
                "script": "76a9145b1b606a13db00b1f2d72e17b1f4acaf6738e8f888ac",
                "address": "bitcoincash:qpd3kcr2z0dspv0j6uhp0v054jhkww8glqcfwd330x"
            }
        ],
        "locktime": 0,
        "hex": "01000000014e87a3c41d3245ec21689228db64e901428e378566beb4256920e22f8fe4a526030000006b483045022100ac252ef8b1e86b5d77d50f149028e4f17a59554e1f2dd64fbd223d2396b0eda202204312ef0c7694d297d4ed5dc4f23b3587a61cd91189b23f1306cff256f60b6849412103a78fbf6f3dfd66621171630e84146e8e1df425365e44f2cef6d65e03f7fed1deffffffff0280380100000000001976a914a928707e4a74740cdbacf87a390c45878f64e2ae88ac6baf9500000000001976a9145b1b606a13db00b1f2d72e17b1f4acaf6738e8f888ac00000000",
        "confirmations": 2453
    }

**Comment by tuxcanfly** [comment]
@Ariel-Li-Yu Thanks, good catch. Can you try with the fix #74 and check if it fixes the issue?
