### ISSUE TITLE
Script flag inconsistency - CHECKDATASIG

### ISSUE THREAD

**Issue by tuxcanfly** [bcoin-org/bcash#78]
`bitcoin-abc` uses the flag `1 << 18` for `SCRIPT_ENABLE_CHECKDATASIG` whereas we use it for `VERIFY_MONOLITH_OPCODES`.

Reminder that we need to take care of this.

Spotted by @rojii

**Comment by rojii** [comment]
Working on the changes. Will report back later tomorrow on irc
