### ISSUE TITLE
Can't createTX() with OP_RETURN output

### ISSUE THREAD

**Issue by gtklocker** [bcoin-org/bcash#95]
The output is considered dust so the function throws, however a tx with an OP_RETURN is still a valid tx.

**Comment by dionyziz** [comment]
Can you try increasing its value?

**Comment by bucko13** [comment]
Yeah, note that even OP_RETURNs should need to pay a fee.

**Comment by gtklocker** [comment]
Is this right? I mean there definitely will be a fee (on the whole transaction) but I've never seen the value of specifically the OP_RETURN output be something other than 0. Example: https://live.blockcypher.com/btc/tx/88f89cecc445d4e62a5d5c2ccbf6e512348b18ff2b9be23473d62f9660629846/

Also, `createrawtransaction` on Bitcoin-ABC when passed a data key will also create a tx with zero value on the OP_RETURN output. And it does get relayed/confirmed just fine.

**Comment by OrfeasLitos** [comment]
It seems like _each_ output needs to be above the dust limit (which in Bitcoin Core with default parameters for a simple P2PKH turns out to be 546 shatoshis): https://www.reddit.com/r/Bitcoin/comments/2unzen/what_is_bitcoins_dust_limit_precisely/ https://github.com/bitcoin/bitcoin/commit/9022aa3

I couldn't find a definitive answer though.

**Comment by gtklocker** [comment]
Again, this is a confirmed Bitcoin transaction from 3 hours ago:

https://live.blockcypher.com/btc/tx/88f89cecc445d4e62a5d5c2ccbf6e512348b18ff2b9be23473d62f9660629846/
http://chainquery.com/bitcoin-api/getrawtransaction/88f89cecc445d4e62a5d5c2ccbf6e512348b18ff2b9be23473d62f9660629846/1

As you can see, the OP_RETURN output has 0 value:

```
...
			{
				"value": 0.00000000,
				"n": 0,
				"scriptPubKey": {
					"asm": "OP_RETURN 6f6d6e69000000000000001f0000000c59684c18",
					"hex": "6a146f6d6e69000000000000001f0000000c59684c18",
					"type": "nulldata"
				}
			},
...
```

**Comment by gtklocker** [comment]
@OrfeasLitos with regards to the bitcoin source you cited, it can easily be seen that there's special treatment for non-spendable outputs (https://github.com/morcos/bitcoin/blob/f4d00e63f7951469c840edede3f675d07249f62a/src/policy/policy.cpp#L34-L35). This would mean that `IsDust` on a 0-value OP_RETURN should evaluate to `0 < 0` which in turn is `false`.

**Comment by OrfeasLitos** [comment]
I think you found here the crucial spot. You can make a PR here if you have the time.

**Comment by gtklocker** [comment]
By the way, OP_RETURN txs don't even go through the `IsDust` check: https://github.com/morcos/bitcoin/blob/f4d00e63f7951469c840edede3f675d07249f62a/src/policy/policy.cpp#L143-L144

**Comment by gtklocker** [comment]
@bucko13 any update on this? There's the exact same issue on bcoin, maybe we should open an issue there?

**Comment by gtklocker** [comment]
Here's a full minimal example which fails:

```javascript
const bcash = require('bcash');
(async () => {
  const node = new bcash.SPVNode({});
  const {wdb} = node.use(bcash.wallet.plugin);
  await node.open();
  await node.connect();

  const wallet = wdb.primary;
  await wallet.send({
    outputs: [bcash.Script.fromNulldata(Buffer.from('foo'))]
  });
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

Output:
```
Error: Output is dust.
    at Wallet.createTX (/home/vagrant/bch-nipopow-prover/node_modules/bcash/lib/wallet/wallet.js:1219:15)
    at Wallet._send (/home/vagrant/bch-nipopow-prover/node_modules/bcash/lib/wallet/wallet.js:1284:28)
    at Wallet.send (/home/vagrant/bch-nipopow-prover/node_modules/bcash/lib/wallet/wallet.js:1269:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gtklocker** [comment]
With regards to your hypothesis, as I stated earlier, the problem in `createTX` ([link to problematic code](https://github.com/bcoin-org/bcash/blob/master/lib/wallet/wallet.js#L1213-L1230)).

As you can see all outputs are tested for dustedness unconditionally, so this also checks the OP_RETURN which fails. At this point `fund` isn't called yet. This can also be seen from the stack trace above.

**Comment by OrfeasLitos** [comment]
Could the above fail because this wallet has no coins? You could try to give it some coins before sending the tx, taking inspiration from here: https://github.com/OrfeasLitos/TrustIsRisk.js/blob/56808e3805b026ab543eef6f26670308e55100fa/test/spv_node.js#L3, https://github.com/OrfeasLitos/TrustIsRisk.js/blob/56808e3805b026ab543eef6f26670308e55100fa/test/spv_node.js#L36, https://github.com/OrfeasLitos/TrustIsRisk.js/blob/56808e3805b026ab543eef6f26670308e55100fa/test/spv_node.js#L178-L182

**Comment by gtklocker** [comment]
No. I've ensured the wallet has enough balance, and can serve the transaction just fine. Creating the tx manually, funding and sending it does work.

**Comment by OrfeasLitos** [comment]
Could you also provide the minimal testcase that works as well? It will make comparison easier.

**Comment by bucko13** [comment]
`outputs` should be an array of output objects. In your example script, you're just passing a `Script` class as an item on the array which `send` won't know how to interpret. Luckily the `Output` class in bcoin/bcash has a `fromScript` method you can use to convert your OP_RETURN script, as seen in the bpanel plugin mentioned above (link to relevant code [here](https://github.com/bpanel-org/publish-data/blob/master/lib/PublishData.js#L35)).

**Comment by gtklocker** [comment]
You're right.
