### ISSUE TITLE
BIP158/157 Support

### ISSUE THREAD

**Issue by floreslorca** [bcoin-org/bcash#97]
Whats the plans of bcash for those bips

**Comment by floreslorca** [comment]
Hi @nodar-chkuaselidze thanks for the answer. btw is there a telegram/gitter/slack for bcoin/bcash?

**Comment by nodar-chkuaselidze** [comment]
Here: http://bcoin.io/slack-signup.html

**Comment by floreslorca** [comment]
thanks
